# Generated by Django 5.0.2 on 2025-12-04 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar_desit_api', '0004_materias'),
    ]

    operations = [
        migrations.AddField(
            model_name='materias',
            name='creditos',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='materias',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='control_escolar_desit_api.maestros'),
        ),
    ]
